language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
install:
  - brew install watchman
  - npm install
before_script:
  - npm test
  - (npm start > packager.log 2>&1 &) && echo $! > packager.pid

script: ./runXcodeTests.sh 8.1

after_script:
  - pkill -9 -F packager.pid
  - cat packager.log
  - rm packager.log
  - rm packager.pid

# Automatically publish the website
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && (cd website; npm install; ./setup.sh; ./publish.sh; echo) || echo'

env:
  - secure: "g8Xjbslq4R+3oLVgBvXM5QhiJ+7q+H+dH4+sXReyyZ64M5gf32U7oOjQNVkdx79dnGFc6a619otGsX4RiEkQlkiR+4uCgJUIgPwN4YFCIgYu4Z/0FnbbRu5yyywh5zv4WwGmAtMkgGztoMBnps5gCiPUM/RGIqwVk0Ghbmh5c2k="

branches:
  only:
    - master
