language: objective-c

osx_image: xcode7.2

cache:
  directories:
    - node_modules
    - .nvm

install:
  - brew reinstall nvm
  - mkdir -p .nvm
  - export NVM_DIR="$PWD/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 5
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - npm config set spin=false
  - npm config set progress=false
  - npm install

script:
- |
  if [ "$TEST_TYPE" = objc ]
  then

    travis_retry ./scripts/objc-test.sh

  elif [ "$TEST_TYPE" = js ]
  then

    npm install github@0.2.4
    cat <(echo eslint; npm run lint --silent -- --format=json; echo flow; npm run flow --silent -- --json) | GITHUB_TOKEN="af6ef0d15709bc91d""06a6217a5a826a226fb57b7" node bots/code-analysis-bot.js
    npm run flow && npm test

  elif [ "$TEST_TYPE" = e2e-objc ]
  then

    travis_retry ./scripts/e2e-test.sh

  else
    echo "Unknown test type: $TEST_TYPE"
    exit 1
  fi

env:
  matrix:
    - TEST_TYPE=objc
    - TEST_TYPE=js
    - TEST_TYPE=e2e-objc

branches:
  only:
    - master
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - bestander@gmail.com
    on_failure: change
    on_success: change
