language: objective-c

osx_image: xcode8

install:
  - mkdir -p /Users/travis/build/facebook/.nvm
  - export NVM_DIR="/Users/travis/build/facebook/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  # TODO npm 2 started stalling on Travis, t11852928

  # Use node 6 because that is what runs on land-blocking tests
  - nvm install 6
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - wget https://github.com/yarnpkg/yarn/releases/download/v0.16.0/yarn-0.16.0.js
  - export yarn="node $(pwd)/yarn-0.16.0.js"
  - $yarn install

script:
  - if [[ "$TEST_TYPE" = objc-ios ]]; then travis_retry travis_wait ./scripts/objc-test-ios.sh; fi
  - if [[ "$TEST_TYPE" = objc-tvos ]]; then travis_retry travis_wait ./scripts/objc-test-tvos.sh; fi
  - if [[ "$TEST_TYPE" = e2e-objc ]]; then node ./scripts/run-ci-e2e-tests.js --ios --js --retries 3; fi
  - if [[ "$TEST_TYPE" = e2e-objc-tvos ]]; then node ./scripts/run-ci-e2e-tests.js --tvos --retries 3; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm run flow check; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm test -- --maxWorkers=1; fi
  - if [[ ( "$TEST_TYPE" = podspecs ) && ( "$TRAVIS_PULL_REQUEST" = "false" ) ]]; then gem install cocoapods && ./scripts/process-podspecs.sh; fi

env:
  matrix:
    - TEST_TYPE=e2e-objc-tvos
    - TEST_TYPE=e2e-objc
    - TEST_TYPE=objc-ios
    - TEST_TYPE=objc-tvos
    - TEST_TYPE=js
    - TEST_TYPE=podspecs

branches:
  only:
    - master
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - mkonicek@fb.com
      - eloy@artsy.net
    on_failure: change
    on_success: change
  slack:
    secure: oQL2C966v7/DtxNqfM7WowjY0R5mgLHR2qHkoucwK5iVrmaptnHr8fq01xlj7VT0kDwNLqT3n4+gtCviGw89lq71m3W76c8Pms/10jpjw+LwAfQPVizNw/Bx8MFNNmjDauK/auFxaybiLZupi7zd4xFGOZvScmFdfD4CAAp2OOA=
    on_pull_requests: false
    on_failure: change
    on_success: change
