language: objective-c

osx_image: xcode7.2

cache:
  directories:
    - node_modules
    - .nvm

install:
  - brew reinstall nvm
  - mkdir -p .nvm
  - export NVM_DIR="$PWD/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 5
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - npm config set spin=false
  - npm config set progress=false
  - npm install

script:
  - npm run flow

env:
  matrix:
    - TEST_TYPE=js

branches:
  only:
    - master
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - bestander@gmail.com
    on_failure: change
    on_success: change
