language: objective-c

osx_image: xcode7.3

install:
  - brew update
  - brew reinstall nvm xctool
  - mkdir -p /Users/travis/build/facebook/.nvm
  - export NVM_DIR="/Users/travis/build/facebook/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
  # testing with npm@2 for diversity, Circle tests with npm@3
  - nvm install 4.4.0
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - npm config set spin=false
  - npm config set progress=false
  - npm install

script:
  - if [[ "$TEST_TYPE" = objc ]]; then travis_retry ./scripts/objc-test.sh; fi
  - if [[ "$TEST_TYPE" = e2e-objc ]]; then travis_retry node ./scripts/run-ci-e2e-tests.js --ios --js; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm run flow check; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm test -- --maxWorkers=1; fi

env:
  matrix:
    - TEST_TYPE=e2e-objc
    - TEST_TYPE=objc
    - TEST_TYPE=js

branches:
  only:
    - master
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - bestander@gmail.com
    on_failure: change
    on_success: change
