language: objective-c

osx_image: xcode8

install:
  - mkdir -p /Users/travis/build/facebook/.nvm
  - export NVM_DIR="/Users/travis/build/facebook/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  # TODO npm 2 started stalling on Travis, t11852928
  - nvm install 5
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - wget https://github.com/yarnpkg/yarn/releases/download/v0.16.0/yarn-0.16.0.js
  - export yarn="node $(pwd)/yarn-0.16.0.js"
  - $yarn install

script:
  - if [[ "$TEST_TYPE" = objc-ios ]]; then travis_retry travis_wait ./scripts/objc-test-ios.sh; fi
  - if [[ "$TEST_TYPE" = objc-tvos ]]; then travis_retry travis_wait ./scripts/objc-test-tvos.sh; fi
  - if [[ "$TEST_TYPE" = e2e-objc ]]; then node ./scripts/run-ci-e2e-tests.js --ios --js --retries 3; fi
  - if [[ "$TEST_TYPE" = e2e-objc-tvos ]]; then node ./scripts/run-ci-e2e-tests.js --tvos --retries 3; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm run flow check; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm test -- --maxWorkers=1; fi

env:
  matrix:
    - TEST_TYPE=e2e-objc-tvos
    - TEST_TYPE=e2e-objc
    - TEST_TYPE=objc-ios
    - TEST_TYPE=objc-tvos
    - TEST_TYPE=js

branches:
  only:
    - master
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - mkonicek@fb.com
    on_failure: change
    on_success: change
