  test_ios:
    when:
      and:
        - equal: [ false, << pipeline.parameters.run_release_workflow >> ]
        - equal: [ false, << pipeline.parameters.run_nightly_workflow >> ]
    jobs:
      - prepare_release:
          name: "prepare_release (dry run test)"
          version: "0.0.0"
          monorepo_packages_version: "0.0.0"
          tag: test
          dry_run: true
      - prepare_hermes_workspace
      - build_android:
          release_type: "dry-run"
      - build_hermesc_linux:
          requires:
            - prepare_hermes_workspace
      - build_hermesc_apple:
          requires:
            - prepare_hermes_workspace
      - build_apple_slices_hermes:
          requires:
            - build_hermesc_apple
          matrix:
            parameters:
              flavor: ["Debug", "Release"]
              slice: ["macosx", "iphoneos", "iphonesimulator", "catalyst"]
      - build_hermes_macos:
          requires:
            - build_apple_slices_hermes
          matrix:
            parameters:
              flavor: ["Debug", "Release"]
      - build_hermesc_windows:
          requires:
            - prepare_hermes_workspace
      - build_npm_package:
          # Build a release package on every untagged commit, but do not publish to npm.
          release_type: "dry-run"
          requires:
            - build_android
            - build_hermesc_linux
            - build_hermes_macos
            - build_hermesc_windows
      - test_ios_template:
          requires:
            - build_npm_package
          name: "Test Template with Ruby 3.2.0"
          ruby_version: "3.2.0"
          architecture: "NewArch"
          flavor: "Debug"
          jsengine: "Hermes"
          use_frameworks: "StaticLibraries"
      - test_ios_template:
          requires:
            - build_npm_package
          matrix:
            parameters:
              flavor: ["Debug", "Release"]
              jsengine: ["Hermes", "JSC"]
              use_frameworks: ["StaticLibraries", "DynamicFrameworks"]
              architecture: ["NewArch", "OldArch"]
            exclude:
              # This config is tested with Ruby 3.2.0. Let's not double test it.
              - flavor: "Debug"
                jsengine: "Hermes"
                use_frameworks: "StaticLibraries"
                architecture: "NewArch"
      - test_ios_rntester:
          requires:
            - build_hermes_macos
          use_frameworks: "DynamicFrameworks"
          ruby_version: "3.2.0"
          matrix:
            parameters:
              jsengine: ["Hermes", "JSC"]
              architecture: ["NewArch", "OldArch"]
      - test_ios_rntester:
          run_unit_tests: true
          use_frameworks: "StaticLibraries"
          ruby_version: "2.6.10"
          requires:
            - build_hermes_macos
          matrix:
            parameters:
              jsengine: ["Hermes", "JSC"]
              architecture: ["NewArch", "OldArch"]
