  tests_js:
    when:
      and:
        - equal: [ false, << pipeline.parameters.run_release_workflow >> ]
        - equal: [ false, << pipeline.parameters.run_nightly_workflow >> ]
        - equal: [ false, << pipeline.parameters.run_prealpha_workflow >> ]
    jobs:
      - test_js:
          run_disabled_tests: false
      - test_js:
          name: test_js_prev_lts
          executor: nodeprevlts
