  tests_android:
    when:
      and:
          - equal: [ false, << pipeline.parameters.run_release_workflow >> ]
          - equal: [ false, << pipeline.parameters.run_nightly_workflow >> ]
          - equal: [ false, << pipeline.parameters.run_prealpha_workflow >> ]
    jobs:
      - prepare_package_for_release:
          name: prepare_package_for_release
          version: ''
          latest : false
          dryrun: true
      - prepare_hermes_workspace
      - build_android:
          release_type: "dry-run"
      - build_hermesc_linux:
          requires:
            - prepare_hermes_workspace
      - build_hermesc_apple:
          requires:
            - prepare_hermes_workspace
      - build_apple_slices_hermes:
          requires:
            - build_hermesc_apple
          matrix:
            parameters:
              flavor: ["Debug", "Release"]
              slice: ["macosx", "iphoneos", "iphonesimulator", "catalyst"]
      - build_hermes_macos:
          requires:
            - build_apple_slices_hermes
          matrix:
            parameters:
              flavor: ["Debug", "Release"]
      - build_hermesc_windows:
          requires:
            - prepare_hermes_workspace
      - build_npm_package:
          # Build a release package on every untagged commit, but do not publish to npm.
          release_type: "dry-run"
          requires:
            - build_android
            - build_hermesc_linux
            - build_hermes_macos
            - build_hermesc_windows
      - test_android:
          requires:
            - build_android
      # - test_e2e_android
      - test_android_template:
          requires:
            - build_npm_package
          matrix:
            parameters:
              architecture: ["NewArch", "OldArch"]
              jsengine: ["Hermes", "JSC"]
              flavor: ["Debug", "Release"]
      - test_windows
