
steps:

  - task: CmdLine@2
    displayName: Configure git
    inputs:
      script: |
        git config --global user.email "53619745+rnbot@users.noreply.github.com"
        git config --global user.name "React-Native Bot"
