name: Apply version label to issue

on:
  issues:
    types: [opened, edited]

jobs:
  add-version-label-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: lucasbento/core-workflow-apply-version-label@v0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
