name: On Issue Labeled
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

permissions:
  contents: write
  issues: write

jobs:
  # Runs automatic checks on issues labeled with "Needs: Triage",
  # then invokes actOnLabel to react to any added labels
  triage-issue:
    runs-on: ubuntu-latest
    if: "${{ github.repository == 'facebook/react-native' && contains(github.event.label.name, 'Needs: Triage :mag:') }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const verifyVersion = require('./.github/workflows/verifyVersion.js')
            const labelToAdd = await verifyVersion(github, context);

            if(labelToAdd) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [labelToAdd]
              })

              const actOnLabel = require('./.github/workflows/actOnLabel.js')
              await actOnLabel(github, context, labelToAdd)
            }
  # Reacts to the label that triggered this workflow (added manually or via other workflows)
  act-on-label:
    runs-on: ubuntu-latest
    if: github.repository == 'facebook/react-native'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const actOnLabel = require('./.github/workflows/actOnLabel.js')
            await actOnLabel(github, context, context.payload.label.name)
