name: Publish Bumped Packages

on:
  push:
    branches:
      - "main"
      - "*-stable"

jobs:
  runs-on: ubuntu-latest
  env:
    GHA_NPM_TOKEN: ${{secrets.GHA_NPM_TOKEN}}
  steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup node.js
      uses: ./.github/actions/setup-node
    - name: Build packages
      command: yarn build
    - name: Set NPM auth token
      run: echo "//registry.npmjs.org/:_authToken=$GHA_NPM_TOKEN" > ~/.npmrc
    - name: Find and publish all bumped packages
      run: node ./scripts/releases-ci/publish-updated-packages.js
