# This jobs runs every day 2 hours after the nightly job for React Native so we can verify how the nightly is behaving.
name: Check Hermes V1 with the nightly build

on:
  workflow_dispatch:
  # nightly build @ 4:15 AM UTC
  schedule:
    - cron: '15 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-nightly:
    runs-on: ubuntu-latest
    if: github.repository == 'facebook/react-native'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check nightly
        run: |
          TODAY=$(date "+%Y%m%d")
          echo "Checking nightly for $TODAY"
          NIGHTLY="$(npm view react-native | grep $TODAY)"
          if [[ -z $NIGHTLY ]]; then
            echo 'Nightly job failed.'
            exit 1
          else
            echo 'Nightly Worked, All Good!'
          fi

  test-hermes-v1-ios:
    uses: ./.github/workflows/test-hermes-v1-ios.yml
    needs: check-nightly

  test-hermes-v1-android:
    uses: ./.github/workflows/test-hermes-v1-android.yml
    needs: check-nightly
